# Generated by Django 3.1.5 on 2021-01-29 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalFinance', '0002_delete_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetcategory',
            name='name',
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='expensecategory',
            name='name',
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='incomecategory',
            name='name',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
