# Generated by Django 3.1.5 on 2021-01-29 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personalFinance', '0003_auto_20210129_1005'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseSubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='personalFinance.expensecategory')),
            ],
        ),
    ]
