# Generated by Django 3.1.5 on 2021-01-29 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personalFinance', '0004_expensesubcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='expenses', to='personalFinance.expensesubcategory'),
        ),
    ]
