# Generated by Django 3.1.5 on 2021-02-15 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalFinance', '0006_auto_20210129_1100'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='position',
            field=models.CharField(choices=[('start', 'start'), ('end', 'end')], default='end', max_length=5),
        ),
    ]
